### ISSUE TITLE
kcl does not exist on https://pypi.python.org/simple/

### ISSUE THREAD

**Issue by davidjp90** [jakeogh/dnsgate#3]
Running python3.4 setup.py install returns the following error for kcl. It seems this does not exist on the python page (https://pypi.python.org/simple/).

#python3.4 setup.py install
running install
running bdist_egg
running egg_info
....
....
....
....
Installed /usr/lib/python3.4/site-packages/dnsgate-0.0.1-py3.4.egg
Processing dependencies for dnsgate==0.0.1
Searching for kcl
Reading https://pypi.python.org/simple/kcl/
Couldn't find index page for 'kcl' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for kcl
error: Could not find suitable distribution for Requirement.parse('kcl')

**Comment by jakeogh** [comment]
Much appreciated, when kcl is a bit more polished I will post it to pypi. For now manually install.
